apiVersion: v1
kind: ReplicationController
metadata:
  name: concourse-postgresql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: concourse-postgresql
    spec:
      containers:
      - name: concourse-postgresql
        image: postgres:9.5
        env:
        - name: POSTGRES_DB
          value: concourse
        - name: POSTGRES_USER
          value: concourse
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: concourse-secrets
              key: postgres-password
        - name: PGDATA
          value: /database
        ports:
        - containerPort: 5432
